kumuluzee:
  name: rso-orders
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  discovery:
    consul:
      agent: http://consul:8500
  cors-filter:
    servlet:
      allow-origin: "*"
rest-properties:
  healthy: true
