apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: joborders
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: joborders
        tier: frontend
    spec:
      containers:
      - image: tilen/job-orders
        name: joborders
        ports:
        - containerPort: 8081
          name: server
          protocol: TCP
        env:
          - name: VERSION
            value: "4"
          - name: LOGSTASH_HOST
            value: "log.tomakic.com"
