apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rso-job
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rso-job
    spec:
      containers:
      - image: tilen/rso-job
        name: rsoapiseed
        ports:
        - containerPort: 3000
          name: server
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
          - name: DEPLOY_VERSION
            value: "%DEPLOY_VERSION%"
